/**
 * Generated by `convex dev`. See note in `dataModel.d.ts`.
 *
 * The hand-rolled stub uses `AnyApi` so callers compile before the CLI runs.
 * After `pnpm convex:dev`, this file is replaced with a strongly-typed tree
 * derived from each module's exported functions.
 */
import type { AnyApi } from "convex/server";

export declare const api: AnyApi;
export declare const internal: AnyApi;
