/**
 * Generated by `convex dev`. See note in `dataModel.d.ts`.
 *
 * Hand-written so the project typechecks before the first `convex dev` run.
 * The CLI replaces this file with a strongly-typed tree derived from each
 * module's exported functions.
 *
 * Adding a new convex/*.ts module: add its alias to `ApiFromModules` below.
 */
import type { ApiFromModules } from "convex/server";

import type * as auditLog from "../auditLog.js";

export declare const api: ApiFromModules<{
  auditLog: typeof auditLog;
}>;

export declare const internal: ApiFromModules<{
  auditLog: typeof auditLog;
}>;
