/**
 * Generated by `convex dev`.
 *
 * This file is an in-repo stub written by hand so the project typechecks before
 * the first `convex dev` run. Once `pnpm convex:dev` runs against a real
 * deployment, the Convex CLI overwrites this file with the canonical generated
 * version. Do not edit by hand after that.
 */
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "convex/server";
import type { GenericId } from "convex/values";

import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type TableNames = TableNamesInDataModel<DataModel>;

export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;

export type Id<
  TableName extends TableNames | "_storage" | "_scheduled_functions",
> = GenericId<TableName>;
